### ISSUE TITLE
Set up for Multi channel audio language channels

### ISSUE THREAD

**Issue by GotoNext** [pkviet/obs-studio#18]
Dear,
I have been testing and was not able to get the multiaudio channels to work correctly,
I try with changeging the Recording to Custom URL ffmpeg , but get errors. Also what would the correct FFmpeg command be if i was to use English, German, French and Dutch audio.
A small example would be great.

**Comment by pkviet** [comment]
Your question does not make clear if you're testing recording or streaming.
Check here: https://github.com/obsproject/obs-studio/wiki/Surround-Sound-Streaming-And-Recording#multilingual-streaming
This does not - can not - work out of the box without backend work because NO service accepts multilingual streams. So the trick here is to split the audio channels in as many standard rtmp streams.
Another option is to have multi-track audio (each language has a separate audio track - instead of being one channel  in a single multichannel audio track); this is supported by mpegts.
For more support, the simpler is to go to obs discord server and ping me there (@pkv)

**Comment by pkviet** [comment]
closing since we sorted this out on discord
