### ISSUE TITLE
Missing dll files

### ISSUE THREAD

**Issue by onegooduser** [pkviet/obs-studio#28]
After installing and upon launching, I get error messages saying these three dll files can't be found:
msvcp140d.dll
ucrtbased.dll
vcruntime140d.dll

**Comment by pkviet** [comment]
that's odd, i don't get it; those are debug dll. The 25.0.8 binary has only RelWithDebInfo dll.
What did you download ? It's working on my side

**Comment by PhotexMedia** [comment]
Having this same issue too, not sure why as I haven't experienced it with previously releases.

Error is from the latest release 25.0.8

**Comment by pkviet** [comment]
ok that's puzzling. Thanks for the confirmation. I have these debug dll, so of course no issues on my side. But they shouldn't be linked in the released binary. Gonna check

**Comment by pkviet** [comment]
until I fix the issue, you can test the binaries here:
https://github.com/pkviet/obs-studio/actions/runs/127599864
As a bonus, you'll have audio bitrate increased to up to 5 Mbs for ffmpeg native aac encoder.

**Comment by pkviet** [comment]
Fixed the issue; will post a fixed build tomorrow.

**Comment by onegooduser** [comment]
Thanks this is great! Any plans to develop this as a plug-in for OBS?

**Comment by pkviet** [comment]
On Thu, Jun 11, 2020, 22:22 onegooduser <notifications@github.com> wrote:

> Thanks this is great! Any plans to develop this as a plug-in for OBS?
>

This ? Meaning increased bitrates for ffmpeg aac ?
Sorry, not sure of what you mean.

**Comment by onegooduser** [comment]
I’m not a dev so forgive me if asking for the moon but...

Could the entire Music Edition idea (basically the enhanced audio output
and monitoring side of things) Be developed as a plug-in for OBS, as
opposed to a complete fork OF OBS?

**Comment by pkviet** [comment]
On Thu, Jun 11, 2020, 22:32 onegooduser <notifications@github.com> wrote:

> I’m not a dev so forgive me if asking for the moon but...
>
> Could the entire Music Edition idea (basically the enhanced audio output
> and monitoring side of things) Be developed as a plug-in for OBS, as
> opposed to a complete fork OF OBS?
>

It's not possible to add the features of OBS ME as a plugin because I
modified libobs the library behind the UI.
It's required to support up to 16 channels and a lot of the new features.
This is unlikely to be merged due to the very small userbase. (I wrote the
code to support up to 7.1 in vanilla obs. The code in  ME is very close.)
The master mixer is a lot of code so it won't be merged into vanilla any
soon.
There'll be a monitoring button though in the next few releases ...

**Comment by pkviet** [comment]
Fixed. Redownload 25.0.8.

**Comment by onegooduser** [comment]
Awesome! Works for me! Thank you so much.
