### ISSUE TITLE
Obs music editions

### ISSUE THREAD

**Issue by alejandroravelo** [pkviet/obs-studio#33]
Hello, a few days ago I installed the version of the obs music editions since I am a dj and the obs websoket plugins does not work with this version, I really need both programs yes or yes, does anyone know any way to make it work for me? Please help me

**Comment by pkviet** [comment]
obs-websocket would have to be recompiled against libobs version in the fork; i haven't done so since I don't use it. I might or might not include it in next update which should a matter of  2-3 weeks (will be released when vanilla obs gets its update, which is soon).
It's a hobby project, done on my free time. So it'll depend on whether I find time.

**Comment by alejandroravelo** [comment]
Thank you friend, I really appreciate the help, thank you
