### ISSUE TITLE
Elgato Streamdeck doesn't work

### ISSUE THREAD

**Issue by aranhawaii** [pkviet/obs-studio#48]
When I try to connect OBS Studio to my Elgato Streamdeck while using OBS ME, it doesn't want to connect. Basically says that the OBS plugin needs to be re-installed, but doing that does nothing. I'm sure it's because a) elgato expects OBS to be installed to the default drive (C:) and b) it's not installing the plug-in to the folder that ME is installed to. Do I just need to copy the plug-in files over to the folder that ME is in? Have you already seen this issue reported to you?

 - OS: Windows 10

**Comment by pkviet** [comment]
OBS ME has a different libobs due to the added capabilities for audio. So obs native plugins won't work out of the box, they need to be recompiled specifically for obs ME. I'll ship obs-websocket with the next release of obs ME but as to streamdeck, I have no plans to compile it specifically for obs ME since I don't use it (my streamdeck is in its box, never had much use for it).
Remember, it's just a hobby project.
