### ISSUE TITLE
[27.0.1] UI bugs (serious)

### ISSUE THREAD

**Issue by Mishasama** [pkviet/obs-studio#59]
1. My mic is stereo, and it was displayed correctly in the 26.0.2-ME, but not now. It always shows as 7.1 channels even after restart obs. (My general channels settings is 7.1)
![image](https://user-images.githubusercontent.com/54498172/126018483-303c6af9-58c3-4444-9929-7bbfc01e2e3d.png)

2. Settings -> Advanced -> Hotkeys
![image](https://user-images.githubusercontent.com/54498172/126016799-d6c6e09b-5c43-440b-b7ea-3e0b9e2fe781.png)
3. Menu -> Tools -> OBS WebSocket
![image](https://user-images.githubusercontent.com/54498172/126020057-6f7a0026-8d3e-4a1e-9501-85ad483f8b13.png)

**Comment by pkviet** [comment]
Not a bug !
It's as intended; I've changed the meters display per this commit: https://github.com/pkviet/obs-studio/commit/5a382f86dce7a4e405bba9de78658583a4536d54
The reason is quite intricate but it solves an old bug in original obs; context is explained here: https://github.com/obsproject/obs-studio/pull/1540
I'll summarize:
- obs processes audio in the pipeline: audio -> resample to output number of channels -> filters -> input meter
- so what is displayed in obs input meter is NOT a clean input but it's been upmixed from stereo to 7.1 in your case.
- why did it show previously only two channels ? because Jim (obs main dev) decided to hide the excess output channels. It works for stereo input but in some more general cases it does not (for instance mono source routed to channel 3 or later).
- so what you are seeing now is the real result of the upmixing of your stereo source; two channels are active (the first two) while the others are not because the resampler matrix for stereo ==> 7.1 is written like this in ffmpeg swresample library.
- there's NO difference in the audio processing so don't worry. It's just a different more accurate display.

**Comment by Mishasama** [comment]
Okay, got your intend and agree, it's much clear now.

What about another two? Do I have to build it myself in the future? Or even have to sync codes to the last release myself? 😅

**Comment by pkviet** [comment]
Ah for 2 and 3 that's just the ini files which need to be updated with the strings. They're in obs-data folder. You can do it manually with a text editor. No big deal. No need to compile anything.

**Comment by Mishasama** [comment]
Er... What's your plan for the future update? I saw you say you won't release any more in the future.
The original OBS will be updated in the future. Should I have to learn how to sync and compile it now for preparation?
(If I want to fix it for other people?)

**Comment by pkviet** [comment]
Well, I think it's not maintainable by somebody else because each obs
update requires extensive rebasing with non trivial, usually, adjustments
to obs ME code ....
If you want to try your luck, you're welcome of course. But the learning
curve will be super steep. You not only need familiarity with obs code but
also with our changes to libobs and UI. Frankly it had become too much of a
hassle so that's the main reason I don't want to maintain. Each obs update
breaks stuff in obs ME which I'd have to fix.
