### ISSUE TITLE
Bug of audio_output_connect()

### ISSUE THREAD

**Issue by Mishasama** [pkviet/obs-studio#69]
[Detail](https://obsproject.com/forum/threads/waveform.151139/post-569043)

Never mind, I just left a heads up.

**Comment by pkviet** [comment]
the bug is because Obs ME is not compatible with third party plugins, unless they're rebuilt against obs ME version of libobs. The support for 9-16 audio channels , master mixer, monitoring etc, requires changes to the libobs library, so other plugins require recompilation.
That said, the plugin seems interesting; maybe i'll compile it.

**Comment by Mishasama** [comment]
Just a note for this issue gets resolved.
https://github.com/phandasm/waveform/releases/tag/v1.4.0
