### ISSUE TITLE
[27.2.4] Meter display incorrectly

### ISSUE THREAD

**Issue by Mishasama** [pkviet/obs-studio#72]
![image](https://user-images.githubusercontent.com/54498172/166195990-35570e6a-eb7c-4ec5-9be7-adaa45b92bd3.png)
With 22.2 channels.

**Comment by Mishasama** [comment]
![image](https://user-images.githubusercontent.com/54498172/167139034-e1fe1128-456c-4eb8-9ece-1afa1048c061.png)
And after restarting OBSME with mute, the new dim style doesn't apply to it.

**Comment by pkviet** [comment]
ok i'll check it out. thx for the report.

**Comment by pkviet** [comment]
i was unable to repro the first bug. Be warend that there's some delay between the master mixer and the input mixer due to processing time.
![obs64_2022-05-06_18-03-11](https://user-images.githubusercontent.com/9283407/167170088-02ce3377-7a46-446c-9d39-33b82b6cfb4d.png)
I repro'd the second bug and fixed it though. I'll post a fixed build once I've checked the other bugs you reported.

**Comment by Mishasama** [comment]
![image](https://user-images.githubusercontent.com/54498172/167508184-d18997a6-8d81-4f64-86fb-85b41c52b0ac.png)
No... I mean these numbers, not the delay.

**Comment by pkviet** [comment]
fixed in 27.2.5
