### ISSUE TITLE
Bundled ffmpeg libraries missing version suffix

### ISSUE THREAD

**Issue by aramg** [pkviet/obs-studio#79]
This seems to be the cause of certain plugins not working (ex DroidCam).
Would be nice to fix if any more future releases are considered.

Expected Behavior:
Include versioned libavcodec dlls, ex  `avcodec-58.dll`, `avformat-58.dll`, …

Current Behavior:
OBS-ME comes with more generic `avcodec.dll`, etc.

**Comment by pkviet** [comment]
Nope. That's not the reason.
Third party plugins can't work because they're compiled against regular libobs.
My fork has a modified libobs.
The ffmpeg dll are compiled with msvc with pdbs, while regular obs cross compiles them on linux without pdbs.
There's no version suffix in msvc. But the version can be read off from properties of the dll. You can rename them if you want. They'll still load but that won't solve your issue.

**Comment by aramg** [comment]
Understood
